name: Dry Run

permissions:
  contents: write # to be able to publish a GitHub release
  id-token: write # to enable use of OIDC for npm provenance
  packages: write

on:
  pull_request:

jobs:
  dry-run-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      #- run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm pkg set publishConfig.provenance=false
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: 'https://npm.pkg.github.com'
          access: restricted
          dry-run: 'true'
